/**
 * error 定义
 */
const SUCCESSED = 0X00000000 //成功
const VSP_START_FAILED = 0x00000001	//VSP初始化失败 
const VSP_STOP_FAILED = 0x00000002	//VSP清除失败
const VAP_LOGIN_FAILED = 0x00000003	//登陆EMS服务器失败
const VAP_GETUSER_FAILED = 0x00000004	//获取用户信息失败
const VAP_GETCAMLIST_FAILED = 0x00000005	//获取摄像头列表失败
const VAP_GETCAMERA_FAILED = 0x00000006	//获取指定摄像头信息失败
const VAP_LOGOUT_FAILED = 0x00000007	//注销EMS失败 
const INSTANCE_HAS_INIT = 0x00000008	//OCX控件已经初始化
const OCX_NOT_INSTANCE = 0x00000009	//OCX没有初始化 
const VAP_LOGIN_FIRST = 0x0000000a	//操作前请首先登陆
//EMS服务器
const PTZ_CMD_FAILED = 0x0000000B	//控制云台命令发送失败
const AUTHEN_CMD_FAILED = 0x0000000C	//用户不具有该权限
const NEED_UPGRADE = 0x00000090	//登陆失败，需要升级控件

/**
 * message 定义
 */
const VSP_START_FAILED_MESSAGE = 'VSP初始化失败'
const VSP_STOP_FAILED_MESSAGE = 'VSP清除失败'
const VAP_LOGIN_FAILED_MESSAGE = '登陆EMS服务器失败'
const VAP_GETUSER_FAILED_MESSAGE = '获取用户信息失败'
const VAP_GETCAMLIST_FAILED_MESSAGE = '获取摄像头列表失败'
const VAP_GETCAMERA_FAILED_MESSAGE = '获取指定摄像头信息失败'
const VAP_LOGOUT_FAILED_MESSAGE = '注销EMS失败' 
const INSTANCE_HAS_INIT_MESSAGE = 'OCX控件已经初始化'
const OCX_NOT_INSTANCE_MESSAGE = 'OCX没有初始化' 
const VAP_LOGIN_FIRST_MESSAGE = '操作前请首先登陆'
//EMS服务器
const PTZ_CMD_FAILED_MESSAGE = '控制云台命令发送失败'
const AUTHEN_CMD_FAILED_MESSAGE = '用户不具有该权限'
const NEED_UPGRADE_MESSAGE = '登陆失败，需要升级控件'

export default {
  SUCCESSED,
  VSP_START_FAILED,
  VSP_STOP_FAILED,
  VAP_LOGIN_FAILED,
  VAP_GETUSER_FAILED,
  VAP_GETCAMLIST_FAILED,
  VAP_GETCAMERA_FAILED,
  VAP_LOGOUT_FAILED,
  INSTANCE_HAS_INIT,
  OCX_NOT_INSTANCE,
  VAP_LOGIN_FIRST,
  //EMS服务器
  PTZ_CMD_FAILED,
  AUTHEN_CMD_FAILED,
  NEED_UPGRADE,

  /**
 * message 定义
 */
VSP_START_FAILED_MESSAGE,
VSP_STOP_FAILED_MESSAGE,
VAP_LOGIN_FAILED_MESSAGE,
VAP_GETUSER_FAILED_MESSAGE,
VAP_GETCAMLIST_FAILED_MESSAGE,
VAP_GETCAMERA_FAILED_MESSAGE,
VAP_LOGOUT_FAILED_MESSAGE,
INSTANCE_HAS_INIT_MESSAGE,
OCX_NOT_INSTANCE_MESSAGE,
VAP_LOGIN_FIRST_MESSAGE,
//EMS服务器
PTZ_CMD_FAILED_MESSAGE,
AUTHEN_CMD_FAILED_MESSAGE,
NEED_UPGRADE_MESSAGE
}